Resources:
  NpCompleteCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: np-complete-doj.in
      SubjectAlternativeNames:
        - "*.np-complete-doj.in"
      DomainValidationOptions:
        - DomainName: np-complete-doj.in
          HostedZoneId: Z1UV67RHS6GARQ
      ValidationMethod: DNS
  SatoSatoZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: sato-sa.to
  SatoSatoCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: sato-sa.to
      SubjectAlternativeNames:
        - "*.sato-sa.to"
      DomainValidationOptions:
        - DomainName: sato-sa.to
          HostedZoneId: !Ref SatoSatoZone
      ValidationMethod: DNS
  MasarakkiZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: masarakki.net
  HismeZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: hisme.net
  HismeRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HismeZone
      RecordSets:
        - Name: hisme.net
          Type: MX
          ResourceRecords:
            - 10 ASPMX.L.GOOGLE.COM
            - 30 ALT1.ASPMX.L.GOOGLE.COM
            - 30 ALT2.ASPMX.L.GOOGLE.COM
            - 50 ASPMX2.GOOGLEMAIL.COM
            - 50 ASPMX3.GOOGLEMAIL.COM
            - 50 ASPMX4.GOOGLEMAIL.COM
            - 50 ASPMX5.GOOGLEMAIL.COM

Outputs:
  SatoSatoZone:
    Value: !Ref SatoSatoZone
  NpCompleteCert:
    Value: !Ref NpCompleteCert
  SatoSatoCert:
    Value: !Ref SatoSatoCert
