Resources:
  SatoSatoZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: sato-sa.to
  SatoSatoCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: sato-sa.to
      SubjectAlternativeNames:
        - "*.sato-sa.to"
      DomainValidationOptions:
        - DomainName: sato-sa.to
          HostedZoneId: !Ref SatoSatoZone
      ValidationMethod: DNS
Outputs:
  SatoSatoZone:
    Value: !Ref SatoSatoZone
  SatoSatoCert:
    Value: !Ref SatoSatoCert
