Resources:
  NpCompleteCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: np-complete-doj.in
      SubjectAlternativeNames:
        - '*.np-complete-doj.in'
      DomainValidationOptions:
        - DomainName: np-complete-doj.in
          HostedZoneId: Z1UV67RHS6GARQ
      ValidationMethod: DNS
  SatoSatoZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: sato-sa.to
  SatoSatoCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: sato-sa.to
      SubjectAlternativeNames:
        - '*.sato-sa.to'
      DomainValidationOptions:
        - DomainName: sato-sa.to
          HostedZoneId: !Ref SatoSatoZone
      ValidationMethod: DNS
  MasarakkiZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: masarakki.net
Outputs:
  SatoSatoZone:
    Value: !Ref SatoSatoZone
  NpCompleteCert:
    Value: !Ref NpCompleteCert
  SatoSatoCert:
    Value: !Ref SatoSatoCert
