name: deploy
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
      - uses: hashicorp/setup-terraform@v3
      - run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
  global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: masarakki-infra-global
          template: global.yml
          no-fail-on-empty-changeset: 1
