name: deploy
on:
  push:
    branches:
      - master
jobs:
  global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: masarakki-infra-global
          template: global.yml
          no-fail-on-empty-changeset: 1
  local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: masarakki-infra
          template: template.yml
          no-fail-on-empty-changeset: 1
